# elasticsearch-configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    #cluster.name: ${CLUSTER_NAME}
    cluster.name: k8s
    #node.name: ${NODE_NAME}
    #discovery.seed_hosts: ${NODE_LIST}
    #cluster.initial_master_nodes: ${MASTER_NODES}

    network.host: 0.0.0.0

    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
