apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-east-1
  version: "1.21"
vpc:
  id: vpc-023252ac2bf858590
  subnets:
    public:
      public-us-east-1a:
        id: subnet-0b8649118691992fd
      public-us-east-1b:
        id: subnet-099763efabf539162
      public-us-east-1c:
        id: subnet-023ed6157382f6c13
    private:
      private-us-east-1a:
        id: subnet-07496fd02a6df0458
      private-us-east-1b:
        id: subnet-0ceffcd9049f8838b
      private-us-east-1c:
        id: subnet-092f87e3ec34c4afe
managedNodeGroups:
- name: managed
  instanceType: t3.small
  desiredCapacity: 3
  minSize: 1
  maxSize: 5
  # volumeSize: 20
  # ssh:
  #   allow: true
  #   publicKeyPath: ~/.ssh/ec2_id_rsa.pub # or publicKeyName: aws_eks-demo_test 
  #   # new feature for restricting SSH access to certain AWS security group IDs
  #   sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
  labels: {role: worker}
  tags:
    nodegroup-role: worker 
  # iam:
  #   withAddonPolicies:
  #       externalDNS: true
  #       certManager: true    
  privateNetworking: true
  subnets:
    - private-us-east-1a
    - private-us-east-1b
    - private-us-east-1c