apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: <your-private-image> ##CHANGE ME 
          name: web
          ports:
            - containerPort: 80 ## CHANGE IT, DEPENDS OF YOUR IMAGE
      imagePullSecrets:
        - name: myregistrykey
