apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.10.2

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: external-dns
  spec:
    template:
      spec:
        containers:
        - name: external-dns
          - args:
              - --source=service
              - --source=ingress
              - --domain-filter=test.my-org.com # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
              - --provider=aws
              - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
              - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
              - --registry=txt
              - --txt-owner-id=my-hostedzone-identifier

    

resources:
  - ./external-dns-all.yaml
